### ISSUE TITLE
Problem adding Namron Z-Wave dimmer 400W (4512710)

### ISSUE THREAD

**Issue by ovestoerholt** [fiLLLip/namron-homey#24]
Adding this dimmer results in error.

Used the following steps:
![Step 1:](https://user-images.githubusercontent.com/1399287/84194371-38567900-aa9d-11ea-8ce5-b9da1f1c1aa5.jpg)
![Step 2:](https://user-images.githubusercontent.com/1399287/84194380-3c829680-aa9d-11ea-88ed-0d80f57ff06e.jpg)
![Step 3:](https://user-images.githubusercontent.com/1399287/84194406-47d5c200-aa9d-11ea-93ba-0d6c6fa5a560.jpg)
![Step 4:](https://user-images.githubusercontent.com/1399287/84194416-4b694900-aa9d-11ea-8b56-ec88f857e266.jpg)
![Step 5:](https://user-images.githubusercontent.com/1399287/84194422-4dcba300-aa9d-11ea-914c-d0ac469c376f.jpg)
![Step 6:](https://user-images.githubusercontent.com/1399287/84194431-502dfd00-aa9d-11ea-87c3-5a86d2b6bebd.jpg)
After a while shows this (probably times out):
![Step 7:](https://user-images.githubusercontent.com/1399287/84194442-52905700-aa9d-11ea-8cca-8693e9fd44d2.jpg)

**Comment by ovestoerholt** [comment]
BTW: 
I am a programmer myself (Android/Spring and Kotlin), but with limited knowledge of Javascript (or Typescript for that matter). Haven't read up on developing for Homey and (if I do) can't expect to master it short term. I can however modify code and create a pull request if desired if you could walk through the structure of a Homey driver with me...

**Comment by fiLLLip** [comment]
I see you have the heatit app installed. Some users have had issues with these two apps installed at the same time and trying to add devices, since both Namron and HeatIt are using white-label products with same manufacturer and device ids. Not sure why this is an issue since you are selecting Namron app in first step. Could you try to remove/deactivate that app and try to include again? Another tip would be to move your Homey within a couple of meters of the dimmer when including. I know HeatIt thermostat needs to do this when trying to include.

Remark: I don't own a Homey myself, I am just maintaining this app since my sister has one :dancers:

**Comment by Exerqtor** [comment]
Exact same issue here, even witout any other apps i stalled. The Homey is located 5M from the dimmer, not abstructed by anything. Debug code: 7436f155-20bc-485a-aa14-bdd8da1e2752.

Edit:
Ok so it apparently was a signal strength issue for me, when i moved the Homey so it was 50cm from the dimmer it worked. But as soon as i put the Homey back where i initialy intended to have it the issues are back. Even though as i mentioned above there only 5meters apart. Don't know if this is a software fix or what, but since both the dimmer and Homey should do 40meters indoors i find this kinda strange.

**Comment by fiLLLip** [comment]
> Exact same issue here, even witout any other apps i stalled. The Homey is located 5M from the dimmer, not abstructed by anything. Debug code: 7436f155-20bc-485a-aa14-bdd8da1e2752.
> 
> Edit:
> Ok so it apparently was a signal strength issue for me, when i moved the Homey so it was 50cm from the dimmer it worked. But as soon as i put the Homey back where i initialy intended to have it the issues are back. Even though as i mentioned above there only 5meters apart. Don't know if this is a software fix or what, but since both the dimmer and Homey should do 40meters indoors i find this kinda strange.

Thanks for digging into it a little more. I find it strange that this issue can be caused by software. Sounds like a hardware/firmware issue to me. Can you see if it has been included as a secure or non-secure device? I have seen samples in other devices that they do really bad in secure inclusions. Unfortunately I cannot tell you how to either check for it nor how to do specific secure/non-secure inclusions.

**Comment by ovestoerholt** [comment]
Actually I just got mine working! :-)
The reason for the error was that I misinterpreted the instructions on this screen:
![image](https://user-images.githubusercontent.com/1399287/86537984-57f18d80-bef3-11ea-9319-ae82740926ee.jpg)

I interpreted is as do **1) or 2)**

but it should be **1) then 2)**

When doing it correctly the dimmer is set up to work just fine! 👍

**Comment by fiLLLip** [comment]
> but it should be **1) then 2)**
> 
> When doing it correctly the dimmer is set up to work just fine! 👍

Interesting! I'll update the instructions. 

@Exerqtor Could you try this?

Edit: These instructions are copied straight outta the manual, so if this is the solution, Elektroimportøren should also be notified: https://products.z-wavealliance.org/ProductManual/File?folder=&filename=product_documents/3641/4512710%20INSTRUCTION%20MANUAL.pdf

**Comment by Exerqtor** [comment]
Hmm, ok i can try doing it that way as well 😅

Edit:
Nah just removed the dimmer from the Z-wave system and placed the Homey 5m from the dimmer and tried re-including it by doing 1) then 2). Same error as before. So in my case it seems like 5m is simply to long away (useless right?).
